name: Build and Release
on:
  push:
    tags:
      - "v*"
jobs:
  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.9"
      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller
      - run: python build_config.py
      - run: |
          brew install create-dmg
          create-dmg \
            --volname "QuantAnalysis" \
            --window-pos 200 120 \
            --window-size 800 400 \
            --icon-size 100 \
            --icon "QuantAnalysis.app" 200 190 \
            --hide-extension "QuantAnalysis.app" \
            --app-drop-link 600 185 \
            "QuantAnalysis.dmg" \
            "dist/QuantAnalysis.app"
      - uses: actions/upload-artifact@v4
        with:
          name: macos-build
          path: QuantAnalysis.dmg

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.9"
      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller
      - run: python build_config.py
      - uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: dist/QuantAnalysis

  create-release:
    needs: [build-macos, build-windows]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
      - uses: softprops/action-gh-release@v1
        with:
          files: |
            macos-build/QuantAnalysis.dmg
            windows-build/QuantAnalysis/QuantAnalysis.exe
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 